
  seleniumhub:
    image: selenium/hub
    ports:
      - "4563:4444"

  firefoxnode:
    image: selenium/node-firefox-debug
    ports:
      - "3754:5900"
    links:
      - seleniumhub
    environment:
      HUB_PORT_4444_TCP_ADDR: seleniumhub
      HUB_PORT_4444_TCP_PORT: '4444'

  chromenode:
    image: selenium/node-chrome-debug
    ports:
      - "3758:5900"
    links:
      - seleniumhub
    environment:
      HUB_PORT_4444_TCP_ADDR: seleniumhub
      HUB_PORT_4444_TCP_PORT: '4444'

  tests:
    build: .
    links:
      - chromenode
      - firefoxnode
    volumes:
      - ./:/service