
  seleniumhub:
    image: selenium/hub
    ports:
      - "4563:4444"

  firefoxnode:
    image: selenium/node-firefox
    links:
      - seleniumhub
    environment:
      HUB_PORT_4444_TCP_ADDR: seleniumhub
      HUB_PORT_4444_TCP_PORT: '4444'

  chromenode:
    image: selenium/node-chrome
    shm_size: 2g
    links:
      - seleniumhub
    environment:
      HUB_PORT_4444_TCP_ADDR: seleniumhub
      HUB_PORT_4444_TCP_PORT: '4444'

  tests:
    build: .
    links:
      - chromenode
    volumes:
      - ./:/service