
  seleniumhub:
    image: selenium/hub
    ports:
      - "4444:4444"
    shm_size: 4g
    volumes:
      - /dev/shm:/dev/shm

  firefoxnode:
    image: selenium/node-firefox
    links:
      - seleniumhub
    environment:
      HUB_PORT_4444_TCP_ADDR: seleniumhub
      HUB_PORT_4444_TCP_PORT: '4444'

  chromenode:
    image: selenium/node-chrome-debug
    shm_size: 2g
    links:
      - seleniumhub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_PORT_4444_TCP_ADDR: seleniumhub
      HUB_PORT_4444_TCP_PORT: '4444'

  tests:
    build: .
    links:
      - chromenode
    volumes:
      - ./:/service
      - /dev/shm:/dev/shm
