version: "3"
services:
  seleniumhub:
    image: selenium/hub
    container_name: seleniumhub
    ports:
        - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
        - seleniumhub
    environment:
        - HUB_PORT_4444_TCP_ADDR=seleniumhub
        - HUB_PORT_4444_TCP_PORT=4444
  firefox:
    image: selenium/node-firefox
    depends_on:
        - seleniumhub
    environment:
        - HUB_PORT_4444_TCP_ADDR=seleniumhub
        - HUB_PORT_4444_TCP_PORT=4444

  tests:
    build: .
    image: notonthehighstreet-end-to-end-tests:latest
    depends_on:
      - chrome
    volumes:
      - ./:/service
