
<% html_report = '--format progress --format html --out=features_report.html' %>
<% rerun = '-f rerun --out rerun.txt' %>


e2e_cognito_check: 'features --format AllureCucumber::Formatter --out --guess <%= html_report %> --tag @e2e_cognito_check'
e2e: 'features --format AllureCucumber::Formatter --out --guess <%= html_report %> --tag @e2e'
cog_e2e: 'features --format AllureCucumber::Formatter --out --guess <%= html_report %> --tag @cog_e2e'
legacy: 'features --format AllureCucumber::Formatter --out --guess <%= html_report %> --tag @legacy'
mobile: "DRIVER='mobile' features <%= html_report %> --format AllureCucumber::Formatter --out --guess --tag @mobile"
cog_mobile_e2e: "DRIVER='mobile' features <%= html_report %> --format AllureCucumber::Formatter --out --guess --tag @cog_mobile_e2e"
error_msg_check: 'features --format AllureCucumber::Formatter --out --guess <%= html_report %> --tag @error_msg_check'

test: 'features --format AllureCucumber::Formatter --out --guess <%= html_report %> --tag @1.01'

payments: 'features --format AllureCucumber::Formatter --out --guess <%= html_report %> --tag @payments'


headless: "DRIVER='headless' features --tag @e2e <%= html_report %>"
rerun: '--guess @rerun.txt'
#allure: '--format AllureCucumber::Formatter --out'