
<% html_report = '--format progress --format html --out=features_report.html' %>
<% rerun = '-f rerun --out rerun.txt' %>

e2e: 'features --guess <%= html_report %> --tag @e2e <%= rerun %>'
mobile:  "DRIVER='mobile' features <%= html_report %> --tag @mobile <%= rerun %>"
headless: "DRIVER='headless' features <%= html_report %> --tag @mobile <%= rerun %>"
demo: 'features --guess <%= html_report %> --tag @demo <%= rerun %>'
mobile_demo: "DRIVER='mobile' features --guess <%= html_report %> --tag @mobile_demo <%= rerun %>"
rerun: '--guess @rerun.txt'