
staging-admin:
  username: 'nothsstagingtester@notonthehighstreet.com'
  password: '6RbxjFWM93'

QA-admin:
  username: 'admin@notonthehighstreet.com'
  password: 'logmein1'

paypal:
  username: 'payments.team-buyer@notonthehighstreet.com'
  password: 'NOTHS2014'